services:
  - type: web
    name: kelo-pds
    runtime: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /xrpc/_health
    disk:
      name: kelo-pds-data
      mountPath: /pds
      sizeGB: 20
    envVars:
      - key: PDS_PORT
        value: "10000"
      - key: PDS_HOSTNAME
        value: pds.kelosocial.eu
      - key: PDS_SERVICE_NAME
        value: Kelo Social PDS
      - key: PDS_SERVICE_HANDLE_DOMAINS
        value: .kelosocial.eu
      - key: PDS_HOME_URL
        value: https://kelosocial.eu
      - key: PDS_LOGO_URL
        value: https://kelosocial.sirv.com/logo.png
      - key: PDS_CONTACT_EMAIL_ADDRESS
        value: support@kelosocial.eu
      - key: PDS_PRIVACY_POLICY_URL
        value: https://kelosocial.eu/privacy
      - key: PDS_TERMS_OF_SERVICE_URL
        value: https://kelosocial.eu/terms

      - key: PDS_DATA_DIRECTORY
        value: /pds
      - key: PDS_BLOBSTORE_DISK_LOCATION
        value: /pds/blocks
      - key: PDS_BLOBSTORE_DISK_TMP_LOCATION
        value: /pds/tmp
      - key: PDS_BLOB_UPLOAD_LIMIT
        value: "104857600"

      - key: PDS_DID_PLC_URL
        value: https://plc.directory
      - key: PDS_BSKY_APP_VIEW_URL
        value: https://api.bsky.app
      - key: PDS_BSKY_APP_VIEW_DID
        value: did:web:api.bsky.app
      - key: PDS_REPORT_SERVICE_URL
        value: https://mod.bsky.app
      - key: PDS_REPORT_SERVICE_DID
        value: did:plc:ar7c4by46qjdydhdevvrndac
      - key: PDS_CRAWLERS
        value: https://bsky.network

      - key: PDS_INVITE_REQUIRED
        value: "false"
      - key: PDS_RATE_LIMITS_ENABLED
        value: "true"
      - key: PDS_DISABLE_SSRF_PROTECTION
        value: "false"
      - key: LOG_ENABLED
        value: "true"
      - key: LOG_LEVEL
        value: info

      # General secrets can safely be generated by Render.
      - key: PDS_JWT_SECRET
        generateValue: true
      - key: PDS_ADMIN_PASSWORD
        generateValue: true
      - key: PDS_DPOP_SECRET
        generateValue: true

      # These values must be entered during Blueprint creation.
      - key: PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
        sync: false
      - key: PDS_EMAIL_SMTP_URL
        sync: false
      - key: PDS_EMAIL_FROM_ADDRESS
        sync: false
